### ISSUE TITLE
exercise 5.4 - can't get it to work in node

### ISSUE THREAD

**Issue by smilingkite** [marijnh/Eloquent-JavaScript#265]
I see that the scripts file in the downloads contains the array with scripts. However, when I download it to my local machine and try to import using the require line, I can't get it to work. It does not recognize 'SCRIPTS'. 
>> require('./path/to/jaques_journal.js') 
I replaced that path with my own path to the file. 

What am I missing? A more elaborate version in the downloads, including file structure, would be welcome.

**Comment by marijnh** [comment]
Node loads files into their own namespace (see CommonJS modules in chapter 10), so the variables they define don't end up in the global scope. Binding the result of calling `require`, as you did, is the right way to handle this. (Adding that line to scripts.js wouldn't help at all, since the binding would still be defined inside of the other module, and not visible to other files.)

**Comment by smilingkite** [comment]
I meant the note at the end of the scripts.js file might be changed so people don't get this mixed up.
