### ISSUE TITLE
Spanish Translation?

### ISSUE THREAD

**Issue by CodeKommissar** [marijnh/Eloquent-JavaScript#301]
Hi Marijnh! I saw yesterday that the third edition of Eloquent JavaScript was already available as a draft and I began wondering if I could help by starting to translate the book to Spanish? When the official version of the book is finished I'd be glad to make the corrections :). Greetings from South America!

**Comment by marijnh** [comment]
Hi. A Spanish translation would be absolutely wonderful. Note that it's a _lot_ of text, and thus a lot of work to translate. But if you can do it, I know such a translation would be valuable to a lot of people.

As the commit history shows, I'm still making adjustments at a rather rapid pace, so it may be worth waiting a few weeks for that to settle down, so that you don't have to sift through huge diffs afterwards. Let me know if you have any questions about the build system or other things.

**Comment by akindofcode** [comment]
I would like to offer my help with the translation to Spanish language.

**Comment by CodeKommissar** [comment]
@marijnh Ahh I understand, then I think it would be better to do as you say and wait for a few weeks to start translating the third edition. About the build system, I'll ask later, but the README seems quite helpful in that aspect.

@akindofcode That would be great :), it would be OK for you/us to start in a few weeks when the book reach a more advanced state?

**Comment by akindofcode** [comment]
@CodeKommissar Sure, just let me know when you're ready to start.

**Comment by cuzox** [comment]
@CodeKommissar & @akindofcode:
I'd love to contribute to the translation process as well!

**Comment by marijnh** [comment]
The text should be stable now (apart from copyediting changes, which probably wouldn't affect a translation anyway)

**Comment by CodeKommissar** [comment]
Alright @marijnh! @akindofcode and @cuzox I created a [Slack Group](https://join.slack.com/t/eloquentjs-spanish/shared_invite/enQtMzIxMjA0NzE2NDIwLTIxNGJhOWY0YTc3MjFmYjNjNmVlN2EwYmM3ZmI1NTNhYWQ3NWU2YzczNTVjZjAzNTQ2NDljNWMyMjMyYzIwZTc) (click the link to join in) to coordinate the translation, we can start tomorrow ^^

**Comment by CodeKommissar** [comment]
Hi @marijnh we've started working on the translation. 

It would be OK for you to create the repository for the spanish version of the book (naming it "JavaScript Elocuente") and giving access to us (@cuzox, @akindofcode and myself). That way no one of the three would own the forked version of the book and it could get more visibility and contributors. Tell us what you think.

**Comment by marijnh** [comment]
Oh, I saw you have repositories with considerable progress in local repositories. Since I don't have a github organization for the book, and I won't be actively involved in the repository, I don't really want to put it at marijnh/JavaScript Elocuente. But I'll gladly publicize your fork when it's done!

**Comment by cuzox** [comment]
Hi @marijnh, I think that's fair. We shall notify you when the translation is complete!

**Comment by ppiamach** [comment]
Hello, I would love to contribute to the Spanish translation of the book if it's not finished yet.

**Comment by ejimz** [comment]
anyone knows the spanish translations status? I would like to help.

**Comment by marijnh** [comment]
I *think* [this repository](https://github.com/eloquentjavascript-es/eloquentjavascript-es) is currently the Spanish translation with the most progress. You could talk to @victorze or directly open pull requests there (or fork again, but it can get really hard to figure out who's doing what if everyone is working in their own fork).

**Comment by alexxonline** [comment]
> I _think_ [this repository](https://github.com/eloquentjavascript-es/eloquentjavascript-es) is currently the Spanish translation with the most progress. You could talk to @victorze or directly open pull requests there (or fork again, but it can get really hard to figure out who's doing what if everyone is working in their own fork).

It seems this repository doesn't exist anymore. Are anyone working on it so we can help?

**Comment by alexxonline** [comment]
> > I _think_ [this repository](https://github.com/eloquentjavascript-es/eloquentjavascript-es) is currently the Spanish translation with the most progress. You could talk to @victorze or directly open pull requests there (or fork again, but it can get really hard to figure out who's doing what if everyone is working in their own fork).
> 
> It seems this repository doesn't exist anymore. Are anyone working on it so we can help?

Nevermind, I found the link https://github.com/marijnh/Eloquent-JavaScript/issues/301

@marijnh Is this still the most advanced translation ? Thanks

**Comment by marijnh** [comment]
> Is this still the most advanced translation ?

Seems so, though it doesn't have a lot of work in it.

**Comment by marijnh** [comment]
I think it would be very useful if someone took a leadership role in the Spanish translation project—I've been approached by a long series of people interested in working on this, and if someone were to put up a repository, link it from here as the place where work currently happens, and communicates with contributors, this could go somewhere. Having a version that's accessible for the half-billion native Spanish speakers on this planet would be _really_ wonderful!

**Comment by marijnh** [comment]
(Of course, if there _is_ an active Spanish translation effort going on somewhere already, do link to it here.)

**Comment by alexxonline** [comment]
To be honest I couldn't do much in this project of translating the book because I didn't have the time. But I'm very interested in making this a reality. The original repo you linked doesn't exists anymore. What do you suggest we should do? Should we create an org and put the link to the repo here? I could do that I could also communicate with contributors and do some work on the repo myself.

**Comment by hectorip** [comment]
Hey! I would like to contribute and start translating myself and I have people interested. I can commit 4 hours a week to make this happen so I would need help to achieve the complete translation soon enough. I think it is a good idea creating an org and start over the translation of the third edition because the work I did was on the second edition.

**Comment by cuzox-sf** [comment]
@CodeKommissar had a repo that had a couple chapters translated, for which I translated a chapter. Not sure what ended up being of it

**Comment by hectorip** [comment]
If you let me I could start the organization today later and make the setup for the public page and, the translation and the building of the partial translation. We could also set some guidelines for contributors.

**Comment by alexxonline** [comment]
Sure! If you start the organization I would like to be added as a member. Also I think we can use some parts of your second edition translation for the part of the book that didn't change for the third edition.
Setting up some guidelines for contributors is a very good idea since I saw a couple of translations that are not so good or it appears that they were made using Google translate.

**Comment by marijnh** [comment]
Repository https://github.com/CodeKommissar/JavaScript-Elocuente still exists and has some work in it. I can't judge the quality of the translation, but it make a good starting point.

**Comment by hectorip** [comment]
@CodeKommissar Creamos la organización, vemos que tienes hasta el capítulo 11. Nos gustaría integrar tu avance o tu repo completo a la organización para tener una fuente oficial de traducción.

**Comment by marijnh** [comment]
Hi all. I'm closing 3rd-edition translation issues to avoid confusion with 4th edition work. Feel free to start a new issue if you're working on the current edition.

See also https://github.com/marijnh/Eloquent-JavaScript/issues/577
